#! /bin/bash
runcmd:
sudo apt update -y
sudo apt install jq -y
sudo mkdir ./metadata
curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq | tee ./metadata
