#! /bin/bash
runcmd:
sudo apt update -y
sudo apt install jq -y
sudo mkdir ./tmp/metadata
[sudo, curl, -H, "Metadata:true", --noproxy, "*", "http://169.254.169.254/metadata/instance?api-version=2020-09-01", -o, ./tmp/metadata] | tee Metadata
